import dynamic from 'next/dynamic';
import Head from 'next/head';
import styled from 'styled-components';

const Wrapper = styled.div`
	width: 100vw;
	height: 100vh;
`;

const Canvas3 = dynamic(() => import('../components/Canvas3'), {
	ssr: false,
	loading: () => <div>loading</div>,
});

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Wrapper>
				<Canvas3 />
			</Wrapper>
		</>
	);
}
